export const ordenesDeEnvios = [
    { numero:123,
    remite: 'Ana Perez',
    recibe:'Martina Fuenmayor',
    desde:  'Madrid',
    hasta: 'Valencia',
    fechaEnvio:'11/15/2023',
    mensaje:'En ruta a almacen destino.',
    estado:'ruta',
    fechaActualizacion:'11/15/2023'
    },
    { numero:1234,
    remite: 'Pedro Ramirez',
    recibe:'Antonio de la Torre',
    desde:  'Barcelona',
    hasta: 'Segovia',
    fechaEnvio:'11/16/2023',
    fechaActualizacion:'11/16/2023',
    mensaje:'En almacen remitente, proximo a salir.',
    estado:'almacen'
    },
    { numero:12345,
        remite: 'Joseph Moreno ',
        recibe:'Maria Segura',
        desde:  'Madrid',
        hasta: 'Barcelona',
        fechaEnvio:'11/16/2023',
        fechaActualizacion:'11/16/2023',
        mensaje:'En almacen remitente, proximo a salir.',
        estado:'almacen'
        },
 { numero:123456,
        remite: 'Francia Rojas',
        recibe:'Eduardo Ruiz',
        desde:  'Segovia',
        hasta: 'Barcelona',
        fechaEnvio:'11/16/2023',
        fechaActualizacion:'11/16/2023',
        mensaje:'En almacen destino, listo para recoger',
        estado:'destino'
        },
]